service: http-handler-ine

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128

functions:
  register:
    handler: src/registrations/handler.register
    role: ${cf:${self:custom.stage}-ine-outputs.RoleARN}
    events:
     - http:
         path: registrations
         method: post
    environment: 
      INE_REGISTRATIONS_TABLE: ${cf:${self:custom.stage}-ine-outputs.IneRegistrationsTableName}

  notifier:
    handler: src/notifications/handler.notify
    role: ${cf:${self:custom.stage}-ine-outputs.RoleARN}
    events:
     - http:
         path: notifications
         method: post
    environment: 
      INE_NOTIFICATIONS_TABLE: ${cf:${self:custom.stage}-ine-outputs.IneNotificationsTableName}
      INE_REGISTRATIONS_TABLE: ${cf:${self:custom.stage}-ine-outputs.IneRegistrationsTableName}
      INE_QUEUE_URL: ${cf:${self:custom.stage}-ine-outputs.QueueURL}

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-ine-registrations